name: Testes da Calculadora

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurando o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Atualizando pip
      run: python -m pip install --upgrade pip

    - name: Rodando os Testes
      run: python -m unittest discover -s ../../ -p "ADI_test.py"
