name: Testes da Calculadora

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurando o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalando Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodando os Testes
      run: python -m unittest discover
